modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "AGPL v3.0"
issueTrackerURL = "https://github.com/Mango-Minecraft-Project/Create_Mortar/issues"
showAsDataPack = true

[[mods]]
modId = "create_mortar"
version = "0.1.3"
displayName = "Create: Mortar - Mango Edition"
description = "A Create Addon Compat Mod / Data Pack"
logoFile = "pack.png"
updateJSONURL = "https://api.modrinth.com/updates/eOYKttUR/forge_updates.json"
authors = "Mango Jelly Pudding"
displayURL = "https://modrinth.com/project/eOYKttUR"

[[dependencies.create_mortar]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
side = "SERVER"

[[dependencies.create_mortar]]
modId = "create"
type = "required"
versionRange = "[0.5.1.f,)"
side = "SERVER"

[[dependencies.create_mortar]]
modId = "tfmg"
type = "optional"
versionRange = "[0.8.0b,)"

[[dependencies.create_mortar]]
modId = "railways"
type = "optional"
versionRange = "[1.6.1,)"

[[dependencies.create_mortar]]
modId = "createbigcannons"
type = "optional"
versionRange = "[0.5.3.b,)"