modLoader = "lowcodefml"
loaderVersion = "[40,)" # 40: 1.18.2, 43: 1.19.2, 47: 1.20.1
license = "AGPL v3.0"
issueTrackerURL = "https://github.com/Mango-Minecraft-Project/Create_Mortar/issues"
showAsDataPack = true

[[mods]]
modId = "create_mortar"
version = "0.1.3"
displayName = "Create: Mortar - Mango Edition"
description = "A Create Addon Compat Mod / Data Pack"
logoFile = "pack.png"
updateJSONURL = "https://api.modrinth.com/updates/eOYKttUR/forge_updates.json"
authors = "Mango Jelly Pudding"
displayURL = "https://modrinth.com/project/eOYKttUR"

[[dependencies.create_mortar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"

[[dependencies.create_mortar]]
modId = "create"
mandatory = true
versionRange = "[0.5.1.f,)"
ordering = "AFTER"

[[dependencies.create_mortar]]
modId = "tfmg"
mandatory = false
versionRange = "[0.8.0b,)"

[[dependencies.create_mortar]]
modId = "railways"
mandatory = false
versionRange = "[1.6.1+forge-mc1.20.1,)"

[[dependencies.create_mortar]]
modId = "createbigcannons"
mandatory = false
versionRange = "[0.5.3.b,)"